CREATE TABLE IF NOT EXISTS categories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    icon TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    category_id INTEGER NOT NULL REFERENCES categories(id),
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    brand TEXT NOT NULL DEFAULT '',
    model TEXT NOT NULL DEFAULT '',
    category_id INTEGER NOT NULL REFERENCES categories(id),
    default_qty INTEGER NOT NULL DEFAULT 1,
    notes TEXT NOT NULL DEFAULT '',
    tag_id INTEGER REFERENCES tags(id)
);

CREATE TABLE IF NOT EXISTS activities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    icon TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS activity_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    activity_id INTEGER NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    is_essential INTEGER NOT NULL DEFAULT 1,
    default_qty INTEGER NOT NULL DEFAULT 1,
    notes TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS activity_slots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    activity_id INTEGER NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    slot_name TEXT NOT NULL,
    category_id INTEGER NOT NULL REFERENCES categories(id),
    is_essential INTEGER NOT NULL DEFAULT 1,
    default_qty INTEGER NOT NULL DEFAULT 1,
    notes TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS activity_slot_tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    slot_id INTEGER NOT NULL REFERENCES activity_slots(id) ON DELETE CASCADE,
    tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    UNIQUE(slot_id, tag_id)
);

CREATE TABLE IF NOT EXISTS tips (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    activity_id INTEGER NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS people (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS trips (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    activity_id INTEGER REFERENCES activities(id),
    start_date TEXT NOT NULL DEFAULT '',
    end_date TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'planning' CHECK(status IN ('planning', 'packing', 'done'))
);

CREATE TABLE IF NOT EXISTS trip_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    item_id INTEGER REFERENCES items(id) ON DELETE SET NULL,
    custom_name TEXT NOT NULL DEFAULT '',
    person_id INTEGER REFERENCES people(id) ON DELETE SET NULL,
    qty INTEGER NOT NULL DEFAULT 1,
    checked INTEGER NOT NULL DEFAULT 0,
    item_status TEXT NOT NULL DEFAULT '' CHECK(item_status IN ('', 'need_buy', 'need_find', 'need_charge', 'need_fetch', 'need_give')),
    notes TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_essential INTEGER NOT NULL DEFAULT 0,
    slot_id INTEGER REFERENCES activity_slots(id)
);

-- Incremental migration: add new columns (safe to re-run via ALTER TABLE tolerance in db.rs)
ALTER TABLE items ADD COLUMN tag_id INTEGER REFERENCES tags(id);
ALTER TABLE trip_items ADD COLUMN is_essential INTEGER NOT NULL DEFAULT 0;
ALTER TABLE trip_items ADD COLUMN slot_id INTEGER REFERENCES activity_slots(id);

-- Item physical attributes (CDDA-style)
ALTER TABLE items ADD COLUMN warmth_rating INTEGER NOT NULL DEFAULT 0;
ALTER TABLE items ADD COLUMN material TEXT NOT NULL DEFAULT '';
ALTER TABLE items ADD COLUMN encumbrance INTEGER NOT NULL DEFAULT 0;
ALTER TABLE items ADD COLUMN waterproof INTEGER NOT NULL DEFAULT 0;
ALTER TABLE items ADD COLUMN weight_grams INTEGER NOT NULL DEFAULT 0;
ALTER TABLE items ADD COLUMN season TEXT NOT NULL DEFAULT '';
ALTER TABLE items ADD COLUMN body_parts TEXT NOT NULL DEFAULT '';
ALTER TABLE items ADD COLUMN env_protection INTEGER NOT NULL DEFAULT 0;
ALTER TABLE items ADD COLUMN durability INTEGER NOT NULL DEFAULT 0;
ALTER TABLE items ADD COLUMN storage_ml INTEGER NOT NULL DEFAULT 0;
ALTER TABLE items ADD COLUMN breathable INTEGER NOT NULL DEFAULT 0
